drop table if exists url_check;
drop table if exists url;
create table url
(
    id         integer generated by default as identity not null,
    name       varchar(255),
    createdAt timestamp,
    constraint pk_url primary key (id)
);

create table url_check
(
    id         integer generated by default as identity not null,
    statusCode integer,
    title varchar(255),
    h1 varchar(255),
    description varchar(255),
    name       varchar(255),
    createdAt timestamp,
    urlId integer,
    constraint pk_url_check primary key (id),
    constraint url_fk foreign key (urlId) references url (id)
);


