-- drop table if exists url_checks;
-- drop table if exists urls;
ALTER TABLE urls DROP CONSTRAINT IF EXISTS pk_url;
ALTER TABLE url_checks DROP CONSTRAINT IF EXISTS pk_url_check;
ALTER TABLE url_checks DROP CONSTRAINT IF EXISTS url_fk;
create table if not exists urls
(
    id         integer generated by default as identity not null,
    name       varchar(255),
    created_at timestamp default CURRENT_TIMESTAMP,
    constraint pk_url primary key (id)
);

create table if not exists url_checks
(
    id         integer generated by default as identity not null,
    status_code integer,
    title varchar(255),
    h1 varchar(255),
    description varchar(255),
    name       varchar(255),
    created_at timestamp default CURRENT_TIMESTAMP,
    url_id integer,
    constraint pk_url_check primary key (id),
    constraint url_fk foreign key (url_id) references urls (id)
);
