-- drop table if exists url_checks;
-- drop table if exists urls;
create table if not exists urls
(
    id         integer generated by default as identity not null primary key,
    name       varchar(255),
    created_at timestamp default CURRENT_TIMESTAMP
);

create table if not exists url_checks
(
    id         integer generated by default as identity not null primary key,
    status_code integer,
    title varchar(255),
    h1 varchar(255),
    description text,
    name       varchar(255),
    created_at timestamp default CURRENT_TIMESTAMP,
    url_id integer,
    constraint url_fk foreign key (url_id) references urls (id)
);
