-- apply changes
create table url (
  id                            integer generated by default as identity not null,
  name                          varchar(255),
  created_at                    timestamp,
  constraint pk_url primary key (id)
);

